/* Scene presentation. Mission access rules and badge thresholds live in index.html. */
const sceneNames={cards:'explorer',pinyin:'pinyin',meaning:'meaning',context:'context',detective:'detective',exam:'champion',secret:'secret'};
const mapPlaces=[
 {id:'cards',x:18,y:43,foot:[24,49],poly:'8% 21%,12% 23%,18% 17%,21% 21%,27% 24%,24% 29%,25% 35%,28% 42%,28% 50%,25% 54%,22% 63%,17% 67%,12% 58%,8% 51%,3% 43%,6% 35%,9% 30%'},
 {id:'pinyin',x:41,y:37,foot:[46,43],poly:'35% 16%,39% 15%,41% 12%,43% 16%,48% 19%,50% 18%,49% 23%,48% 25%,49% 34%,52% 37%,50% 43%,46% 48%,36% 47%,31% 40%,30% 36%,33% 29%,33% 21%'},
 {id:'meaning',x:65,y:47,foot:[69,54],poly:'57% 27%,62% 25%,63% 22%,65% 24%,68% 24%,70% 23%,73% 27%,71% 30%,72% 37%,76% 39%,77% 49%,74% 55%,69% 59%,63% 63%,58% 56%,53% 48%,54% 43%,57% 37%'},
 {id:'context',x:44,y:68,foot:[54,71],poly:'31% 52%,32% 48%,35% 49%,39% 47%,44% 50%,48% 48%,51% 52%,51% 57%,55% 61%,56% 68%,59% 70%,57% 75%,50% 78%,46% 87%,40% 84%,36% 77%,29% 70%,28% 65%,30% 59%'},
 {id:'detective',x:81,y:77,foot:[86,84],poly:'75% 53%,78% 52%,79% 49%,80% 52%,84% 53%,88% 53%,88% 57%,87% 61%,90% 67%,91% 72%,94% 74%,94% 82%,90% 87%,83% 94%,77% 88%,72% 87%,68% 80%,66% 75%,70% 68%,74% 64%'},
 {id:'exam',x:88,y:31,foot:[91,38],poly:'81% 14%,84% 13%,86% 10%,88% 8%,91% 12%,95% 14%,94% 18%,95% 24%,97% 28%,98% 34%,94% 38%,91% 45%,87% 42%,81% 38%,78% 31%,80% 24%'}
];
let pendingJourney=null,journeyTimers=[],journeyFrame=0,hoverTimer,selectedPlace=null,pinnedPlace=false,uiMuted=false;
try{uiMuted=localStorage.getItem('wordmaster_sound')==='off'}catch{}
function badgeFile(id){return `assets/badges/badge-${sceneNames[id]}.png`}
function badgeArt(id,p,earned){return `<span class="badge-art ${earned?'lit':''}" style="--charge:${earned?100:Math.min(p,95)}%"><img src="${badgeFile(id)}" alt="" class="badge-gray"><img src="${badgeFile(id)}" alt="" class="badge-color"></span>`}
function renderBadgeGallery(){badgeWall.innerHTML=[...MISSIONS,SECRET].map(m=>{const done=m.id==='secret'?allEarned():badgeEarned(m.id),p=m.id==='secret'?MISSIONS.filter(x=>badgeEarned(x.id)).length/6*100:missionProgress(m.id);return `<div class="wall-badge ${done?'unlocked':''}">${badgeArt(m.id,p,done)}<p>${m.id==='secret'&&!done?'隐藏徽章':m.name}</p><small>${done?'已点亮':Math.round(p)+'% 充能'}</small>${done?`<button class="top-btn" onclick="downloadNamedBadge('${m.id}')">下载徽章</button>`:''}</div>`}).join('')}
function enterRoom(id){cancelAnimationFrame(journeyFrame);document.body.dataset.room=sceneNames[id];document.body.style.setProperty('--room-art',`url("assets/level-backgrounds/level-${sceneNames[id]}.webp")`);closeMapPanel();}
function leaveRoom(){delete document.body.dataset.room;}
function queueMapJourney(id,completed=false){pendingJourney={id,newlyUnlocked:completed}}
function resetMapJourney(){pendingJourney=null;try{localStorage.removeItem('wordmaster_map_place_2g3_v2')}catch{}}
function savedMapPlace(){try{return localStorage.getItem('wordmaster_map_place_2g3_v2')}catch{return null}}
function renderAdventureMap(){entryJourneyToken++;entryJourneyActive=false;cancelAnimationFrame(journeyFrame);prepareWalkingArt();journeyTimers.forEach(clearTimeout);journeyTimers=[];
missionGrid.className='scene-scroll';missionGrid.innerHTML=`<div class="map-world"><img class="map-picture" src="assets/map-clean.webp" alt="六座由石桥相连的词语奇境，选择一座建筑进入任务" draggable="false">${mapPlaces.map(n=>{const m=MISSIONS.find(m=>m.id===n.id),done=badgeEarned(n.id),locked=!missionAvailable(n.id);return `<button type="button" class="island ${locked?'is-gray is-locked':done?'is-lit':'is-current'}" data-place="${n.id}" style="clip-path:polygon(${n.poly})" aria-label="${m.name}，${done?'已点亮':locked?'完成前置任务后解锁':'已开启，可以进入'}" aria-expanded="false" aria-controls="mapPanel"><img src="assets/map-clean.webp" alt="" draggable="false"></button><button class="place-label ${locked?'is-locked':done?'is-lit':'is-current'}" style="left:${n.x}%;top:${n.y}%" data-place="${n.id}" aria-expanded="false" aria-controls="mapPanel">${m.name}<span>${locked?'未解锁':done?'已通关':'去探索'}</span></button>`}).join('')}<div class="map-party" aria-hidden="true"><span class="party-halo"></span><span class="party-beacon">我们在这里</span><span class="party-walk"></span><img src="assets/characters/panda-hero-hanfu.png" alt=""><img src="assets/characters/otter-companion-hanfu.png" alt=""></div><div class="map-panel hidden" id="mapPanel"></div><p class="map-tip">先完成藏书阁 · 再自由探索四关</p></div><div class="map-toolbar"><button class="top-btn" id="showMyBadges">我的徽章</button><button class="top-btn" id="findParty">找到伙伴</button><span>小屏幕可左右滑动地图</span></div><p id="journeyStatus" class="sr-only" aria-live="polite"></p>`;
const world=missionGrid.querySelector('.map-world');world.querySelectorAll('[data-place]').forEach(button=>{button.addEventListener('pointerenter',e=>{if(e.pointerType==='mouse'&&!pinnedPlace){clearTimeout(hoverTimer);hoverTimer=setTimeout(()=>showMapPanel(button.dataset.place),160)}});button.addEventListener('focus',()=>{pinnedPlace=true;showMapPanel(button.dataset.place)});button.addEventListener('click',()=>{pinnedPlace=true;showMapPanel(button.dataset.place)});});world.addEventListener('pointerleave',()=>{hoverTimer=setTimeout(closeMapPanel,180)});world.addEventListener('pointerenter',()=>clearTimeout(hoverTimer));world.addEventListener('click',e=>{if(!e.target.closest('[data-place],.map-panel'))closeMapPanel()});world.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMapPanel();e.target.blur()}});world.addEventListener('focusout',e=>{if(!world.contains(e.relatedTarget))closeMapPanel()});document.getElementById('showMyBadges').onclick=()=>badgeWall.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth',block:'center'});
document.getElementById('findParty').onclick=()=>revealParty(true);const old=mapPlaces.find(n=>n.id===savedMapPlace());placeParty(old?.foot||[17,87]);if(pendingJourney){const target=mapPlaces.find(n=>n.id===pendingJourney.id),newlyUnlocked=pendingJourney.newlyUnlocked;pendingJourney=null;if(target){journeyFrame=requestAnimationFrame(()=>requestAnimationFrame(()=>animateJourney(old,target,newlyUnlocked)))}}}
function showMapPanel(id){if(entryJourneyActive)return;clearTimeout(hoverTimer);selectedPlace=id;const n=mapPlaces.find(n=>n.id===id),m=MISSIONS.find(m=>m.id===id),locked=!missionAvailable(id);const panel=document.getElementById('mapPanel');panel.innerHTML=`<button class="panel-close" aria-label="关闭介绍">×</button><h3>${m.name}</h3><p>${locked?missionLockMessage(id):m.desc}</p><div class="panel-charge">${badgeArt(id,missionProgress(id),badgeEarned(id))}<span>${badgeEarned(id)?'徽章已点亮':`徽章充能 ${missionProgress(id)}%`}</span></div><button class="room-enter" ${locked?'disabled':''}>${locked?'等待解锁':id==='cards'?'进入藏书阁':'进入关卡 · 6题'}</button>`;panel.style.left=`${Math.min(77,Math.max(15,n.x))}%`;panel.style.top=`${n.y>55?n.y-34:n.y+6}%`;panel.classList.remove('hidden');panel.onpointerenter=()=>clearTimeout(hoverTimer);panel.querySelector('.panel-close').onclick=closeMapPanel;panel.querySelector('.room-enter').onclick=()=>walkIntoMission(id);missionGrid.querySelectorAll('[data-place]').forEach(b=>b.setAttribute('aria-expanded',String(b.dataset.place===id)));}
function closeMapPanel(){document.getElementById('mapPanel')?.classList.add('hidden');document.querySelectorAll('[data-place]').forEach(b=>b.setAttribute('aria-expanded','false'));selectedPlace=null;pinnedPlace=false;clearTimeout(hoverTimer);}
function placeParty(point){const p=document.querySelector('.map-party');if(!p)return;p.style.left=point[0]+'%';p.style.top=point[1]+'%'}
function animateJourney(old,target,newlyUnlocked=false,onArrival=null){const p=document.querySelector('.map-party');const routes={cards:{pinyin:[[28,43],[33,46]],context:[[29,48],[35,55]]},pinyin:{meaning:[[52,39],[59,43]]},meaning:{exam:[[76,44],[83,37]],context:[[63,58],[57,63]]},context:{detective:[[59,65],[64,62],[74,74]]}};const graph={};for(const [a,edges] of Object.entries(routes))for(const [b,points] of Object.entries(edges)){(graph[a]??={})[b]=points;(graph[b]??={})[a]=[...points].reverse()}let chain=[old?.id||'cards'];const queue=[chain],seen=new Set();while(queue.length){const route=queue.shift(),last=route.at(-1);if(last===target.id){chain=route;break}if(seen.has(last))continue;seen.add(last);for(const next of Object.keys(graph[last]||{}))queue.push([...route,next])}const path=[old?.foot||[17,87]];if(!old)path.push([22,69],mapPlaces[0].foot);for(let i=1;i<chain.length;i++)path.push(...graph[chain[i-1]][chain[i]],mapPlaces.find(n=>n.id===chain[i]).foot);if(onArrival&&old?.id===target.id)path.push([target.foot[0]-2,target.foot[1]+2]);path.push(target.foot);const segments=path.slice(1).map((point,i)=>({from:path[i],to:point,length:Math.hypot(point[0]-path[i][0],(point[1]-path[i][1])*.563)})).filter(s=>s.length>.01),total=segments.reduce((sum,s)=>sum+s.length,0);const arrive=()=>{p.classList.remove('traveling');try{localStorage.setItem('wordmaster_map_place_2g3_v2',target.id)}catch{}document.querySelector(`[data-place="${target.id}"]`)?.classList.add('just-visited');document.getElementById('journeyStatus').textContent='伙伴已来到'+MISSIONS.find(m=>m.id===target.id).name;revealParty(false,newlyUnlocked);playChime();onArrival?.()};if(!total){arrive();return}const duration=Math.min(3200,Math.max(1800,total*45));p.style.transition='none';p.classList.remove('arrived');p.classList.add('traveling');let started;const tick=time=>{if(!p.isConnected||document.body.dataset.room)return;started??=time;const progress=Math.min(1,(time-started)/duration);let distance=progress*total,segment=segments[segments.length-1];for(const candidate of segments){segment=candidate;if(distance<=candidate.length)break;distance-=candidate.length}const t=Math.min(1,distance/segment.length);p.dataset.facing=segment.to[0]<segment.from[0]?'left':'right';placeParty([segment.from[0]+(segment.to[0]-segment.from[0])*t,segment.from[1]+(segment.to[1]-segment.from[1])*t]);if(progress<1)journeyFrame=requestAnimationFrame(tick);else{placeParty(target.foot);arrive()}};journeyFrame=requestAnimationFrame(tick);}
let walkingArtPromise;
function prepareWalkingArt(){if(walkingArtPromise)return walkingArtPromise;walkingArtPromise=(async()=>{try{const im=new Image();im.src='assets/characters/party-walk-source.png';await im.decode();const canvas=document.createElement('canvas');canvas.width=im.width;canvas.height=im.height;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(im,0,0);const pixels=ctx.getImageData(0,0,im.width,im.height),d=pixels.data;for(let i=0;i<d.length;i+=4){const r=d[i],g=d[i+1],b=d[i+2],key=Math.min(r,b)-g;if(key>90&&r>135&&b>135){d[i+3]=Math.round(d[i+3]*(1-Math.min(1,(key-90)/65)));if(d[i+3]){d[i]=Math.min(r,g+55);d[i+2]=Math.min(b,g+55)}}}ctx.putImageData(pixels,0,0);document.documentElement.style.setProperty('--walking-art',`url("${canvas.toDataURL()}")`);document.documentElement.classList.add('walking-ready')}catch{ /* Keep the supplied cutout characters visible if decoding fails. */ }})();return walkingArtPromise;}

function playChime(){if(uiMuted)return;try{const audio=new (window.AudioContext||window.webkitAudioContext)();[523,659,784].forEach((f,i)=>{const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=f;const t=audio.currentTime+i*.08;g.gain.setValueAtTime(.025,t);g.gain.exponentialRampToValueAtTime(.001,t+.18);o.start(t);o.stop(t+.19)});setTimeout(()=>audio.close(),700)}catch{}}
async function downloadSceneBadge(id){if(!(id==='secret'?allEarned():badgeEarned(id)))return;const item=id==='secret'?SECRET:MISSIONS.find(m=>m.id===id),im=new Image();im.src=badgeFile(id);try{await im.decode()}catch{alert('徽章图片暂时未载入，请稍后再试。');return}const c=document.createElement('canvas');c.width=c.height=1080;const x=c.getContext('2d'),g=x.createLinearGradient(0,0,1080,1080);g.addColorStop(0,'#082f35');g.addColorStop(1,'#17685b');x.fillStyle=g;x.fillRect(0,0,1080,1080);x.strokeStyle='#e8c775';x.lineWidth=8;x.strokeRect(30,30,1020,1020);x.textAlign='center';x.fillStyle='#fff0be';x.font='bold 54px sans-serif';x.fillText('词光奇境大冒险',540,110);x.drawImage(im,265,165,550,550);x.font='bold 62px sans-serif';x.fillText(item.name,540,770);x.fillStyle='#fff';x.font='36px sans-serif';x.fillText(`获得者：${state.profile.name}`,540,840);x.font='30px sans-serif';x.fillText(`班级：${state.profile.className}　学号：${state.profile.index||'—'}`,540,900);x.font='24px sans-serif';x.fillText(`完成日期：${new Date().toLocaleDateString('zh-SG')}`,540,970);const a=document.createElement('a');a.download=`${state.profile.name}_${item.name}.png`;a.href=c.toDataURL('image/png');a.click();}

function revealParty(scroll=false,newlyUnlocked=false){const p=document.querySelector('.map-party');if(!p)return;p.classList.add('arrived');p.querySelector('.party-beacon').textContent=newlyUnlocked?'徽章点亮啦！':'我们在这里';if(scroll)p.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth',block:'center',inline:'center'});}

let entryJourneyActive=false,entryJourneyToken=0;
async function walkIntoMission(id){
 if(entryJourneyActive||!missionAvailable(id))return;
 if(!state.profile.name){openProfile();return}
 const target=mapPlaces.find(n=>n.id===id),party=document.querySelector('.map-party');if(!target||!party)return;
 entryJourneyActive=true;const token=++entryJourneyToken;cancelAnimationFrame(journeyFrame);closeMapPanel();pendingJourney=null;
 const previous=mapPlaces.find(n=>n.id===savedMapPlace());
 const current=[parseFloat(party.style.left),parseFloat(party.style.top)];
 const old=previous?{...previous,foot:current}:null;
 const world=party.closest('.map-world');world.setAttribute('aria-busy','true');
 document.getElementById('journeyStatus').textContent='伙伴正在走向'+MISSIONS.find(m=>m.id===id).name;
 revealParty(true);await prepareWalkingArt();
 if(token!==entryJourneyToken||!party.isConnected)return;
 animateJourney(old,target,false,()=>{
  const delay=350;
  journeyTimers.push(setTimeout(()=>{if(token!==entryJourneyToken||!party.isConnected)return;entryJourneyActive=false;world.removeAttribute('aria-busy');startMission(id)},delay));
 });
}

let badgeArrivalTimer;
function animateBadgeArrival(){
 clearTimeout(badgeArrivalTimer);
 const card=unlockModal.querySelector('.unlock-card');
 card.classList.remove('badge-arriving');
 const medal=unlockMedal,cardBox=card.getBoundingClientRect(),medalBox=medal.getBoundingClientRect();
 const peak=Math.max(1,Math.min(cardBox.width*.96,innerWidth-40,innerHeight*.65)/medalBox.width);
 const shift=cardBox.top+cardBox.height/2-(medalBox.top+medalBox.height/2);
 card.style.setProperty('--badge-peak',String(peak));card.style.setProperty('--badge-rise',shift+'px');
 void card.offsetWidth;card.classList.add('badge-arriving');
 window.GameEffects?.play('badge');
 downloadBadge.disabled=true;closeUnlock.disabled=true;
 const finish=()=>{clearTimeout(badgeArrivalTimer);medal.removeEventListener('animationend',done);card.classList.remove('badge-arriving');downloadBadge.disabled=false;closeUnlock.disabled=false;closeUnlock.focus()};
 const done=e=>{if(e.target===medal&&e.animationName==='badgeTriumph')finish()};
 medal.addEventListener('animationend',done);
 badgeArrivalTimer=setTimeout(finish,3250);
}
